export const SET_PRODUCT_TO_WISHLIST = 'SET_PRODUCT_TO_WISHLIST';
export const GET_CAROUSEL_ARRIVALS_ERROR = 'GET_CAROUSEL_ARRIVALS_ERROR';
export const GET_CAROUSEL_ARRIVALS_SUCCESS = 'GET_CAROUSEL_ARRIVALS_SUCCESS';
export const SET_PRODUCT_TO_CART = 'SET_PRODUCT_TO_CART';
export const GET_CAROUSEL_ARRIVALS_INIT = 'GET_CAROUSEL_ARRIVALS_INIT';
