export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_COLORS = 'GET_COLORS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_FILTERED_PRODUCTS_INIT = 'GET_FILTERED_PRODUCTS_INIT';
export const GET_FILTERED_PRODUCTS_SUCCESS = 'GET_FILTERED_PRODUCTS_SUCCESS';
export const GET_FILTERED_PRODUCTS_ERROR = 'GET_FILTERED_PRODUCTS_ERROR';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';
export const LOAD_MORE_PRODUCTS = 'LOAD_MORE_PRODUCTS';
