export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_COLORS = 'GET_COLORS';
export const GET_BRANDS = 'GET_BRANDS';
export const GET_FILTERED_PRODUCTS_INIT = 'GET_FILTERED_PRODUCTS_INIT';
export const GET_FILTERED_PRODUCTS_SUCCESS = 'GET_FILTERED_PRODUCTS_SUCCESS';
export const GET_FILTERED_PRODUCTS_ERROR = 'GET_FILTERED_PRODUCTS_ERROR';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';
